### ISSUE TITLE
部分未汉化 小地图

### ISSUE THREAD

**Issue by Hoicey522** [DreamingLri/xaero-map-chinese#1]
未汉化内容：
![屏幕截图 2024-11-03 193043](https://github.com/user-attachments/assets/88c1d53f-6b8a-4766-8efd-a7a8fd4d7b4b)
![屏幕截图 2024-11-03 193046](https://github.com/user-attachments/assets/e41f5177-b8eb-4ce2-b02a-465e702efe54)

**Comment by DreamingLri** [comment]
大概率是xaero新增的内容，有空翻修一下

**Comment by Hoicey522** [comment]
辛苦啦，可以的话发下赞助方式

**Comment by DreamingLri** [comment]
感谢您的好意，纯粹为爱发电（其实是我自己看不下去中英文混杂才做的）

**Comment by DreamingLri** [comment]
已在 [v1.0.2](https://github.com/DreamingLri/xaero-map-chinese/releases/tag/v1.0.2)添加翻译
