### ISSUE TITLE
已汉化内容重新变回英文

### ISSUE THREAD

**Issue by Hoicey522** [DreamingLri/xaero-map-chinese#2]
![image](https://github.com/user-attachments/assets/31b029ee-1c15-4381-b8b5-dbe364b817c8)
![image](https://github.com/user-attachments/assets/2010b617-19c1-49e9-b2e2-a4b5eed8d2c3)

**Comment by Hoicey522** [comment]
而且新内容并没有汉化:(

**Comment by DreamingLri** [comment]
汉化本身没问题，是程序打包的时候没有把汉化的json打包进去，我修理一下（

**Comment by DreamingLri** [comment]
在 `v1.0.3` 中已解决
