### ISSUE TITLE
申请传播许可

### ISSUE THREAD

**Issue by lvya3034** [DreamingLri/xaero-map-chinese#3]
我想要在自己的B站视频**简介**中贴出此汉化的源链接（github和modrinth）
视频内容不包含此汉化，但视频被我标记为原创，因此向您申请传播许可
以下是**两个**视频链接：
https://www.bilibili.com/video/BV1oZUhY5EMq
https://www.bilibili.com/video/BV1FzUsYPE43

同时向您_询问_**以后**在各种平台的作品（如视频）中呈现此汉化的意向：
1.是否允许
2.是否每次都要得到您的许可
3.产生的盈利是否需要与您协商
4.是否限制平台，如果是，请说明
5.是否需要控制传播范围，如果是，请说明
6.是否限制传播形式，如果是，请说明
7.其他，如有请补充

您完全可以不对_询问_的部分或全部做出回答
祝您生活愉快！

**Comment by DreamingLri** [comment]
只要挂上github链接即可，但是不可以将汉化源文件单独上传到网盘上进行二次传播，打包成整合包是随意的，其它的内容均不限制

关于国内连不上github的问题可以提供这个汉化包的modrinth[链接](https://modrinth.com/resourcepack/xaero-map-chinese)，感谢您对模组教程的贡献❤️
