### ISSUE TITLE
readme超链接地址错误

### ISSUE THREAD

**Issue by lvya3034** [DreamingLri/xaero-map-chinese#4]
![Screenshot_2024-11-19-20-53-59-703_mark via-edit](https://github.com/user-attachments/assets/5ecd4ca0-4198-48c3-8ff8-cab2ff9e80cd)
在点击图中画圈的Release后，跳转到了masa mods的的汉化包Release
![Screenshot_2024-11-19-20-54-14-564_mark via](https://github.com/user-attachments/assets/15e271d2-f941-4f69-9edc-0b815147296d)
这应该不是刻意的设计吧。。。
复现方式：README-如何使用-Release
点击蓝色超链接即可复现

**Comment by DreamingLri** [comment]
啊这，应该是我直接复制粘贴没有review导致的，这就修一下

**Comment by DreamingLri** [comment]
已解决
